### ISSUE TITLE
File modification on dependencies

### ISSUE THREAD

**Issue by jschepers** [cihga39871/Pipelines.jl#14]
Hi, 
I'm thinking about using your Pipelines.jl package to make my research project reproducible. One thing @behinger and me were wondering about is whether there is also a functionality to check for file modifications in the input file of a task.

To give an example, imagine I defined three different steps and then change the script for the second step such that the data created by it is different. Then I'd like to not rerun step 1 since nothing changes, rerun step 2 because the script changed and also rerun step 3 since the output of step 2 (which is the input to step 3 changed). Would this be possible with Pipelines.jl?

I saw in the documentation that one can check for the existence of input files and that an id_file is created based on the inputs and outputs but I am not sure whether it's only based on the variable names/types or also on the content or last modification time stamp.

Best,
Judith

**Comment by cihga39871** [comment]
Hi @jschepers , 
Pipelines decides whether re-run by checking time stamps and sizes of both input and output files (directories are excluded).

**Comment by cihga39871** [comment]
This behavior is documented [here](https://cihga39871.github.io/Pipelines.jl/stable/API/#Pipelines.create_run_id_file)

**Comment by behinger** [comment]
hey, thanks! 

Just to be clear, for a potential re-run, pipelines checks the whole content of the run-id file - which includes in column 2 the timestamp. Can pipelines then use this timestamp to check whether timestamps of e.g. a non-julia input files are newer, and if yes, rerun the step then?

maybe we missed where exactly such behavior is described - I'm a bit confused by the docstring

**Comment by cihga39871** [comment]
Yes - pipelines checks the whole content of the run-id file - which includes in column 2 the timestamp.

Can you define what non-julia input files are? The input files are usually not ending with .jl

**Comment by behinger** [comment]
THanks a lot for your patience with me. I really appreciate it!

I am looking at pipelines similar to a Makefile, the functionality I would need, is to compare the timestamp of the run-id file (c.f. make the inputfile a dependency in make), with the timestamp of an input file (declared via input = "path/to/fileA"). As I understand right now, if fileA is updated, Pipelines has no handle to detect that and run the job again.

Does this make the use case clearer? Apologies for jumping in directly and potentially naively, @jschepers played around much more with the package than I have

**Comment by cihga39871** [comment]
Thank you for clarifying!

Pipelines support what you mentioned about Makefile. (Checking methods are slightly different. Makefile checks whether files are newer, while Pipelines check whether timestamp and file size *equal* to the records in the run ID file.)


I will show you a code:

Create a small script called "prog1.jl" first:
```julia
x = open(ARGS[1], "w+")
println(x, ARGS[2])
close(x)
```

Then, open a Julia REPL to try Pipelines:

```julia
julia> using Pipelines

julia> prog = CmdProgram(cmd = `julia prog1.jl FILE CONTENT`, inputs = ["FILE", "CONTENT"])
CmdProgram:
  name             → Command Program
  id_file          → 
  info_before      → auto
  info_after       → auto
  cmd_dependencies → <empty>
  arg_inputs       → FILE    :: Any (required)
                     CONTENT :: Any (required)
  validate_inputs  → do_nothing
  prerequisites    → do_nothing
  cmd              → `julia prog1.jl FILE CONTENT`
  infer_outputs    → do_nothing
  arg_outputs      → <Arg empty>
  validate_outputs → do_nothing
  wrap_up          → do_nothing
  arg_forward      → <empty>

julia> run(prog, FILE="file1", CONTENT="abcdf")
┌ Info: 2023-07-14 16:16:18 Started: Command Program
│   command_template = `julia prog1.jl FILE CONTENT`
│   run_id = UUID("d6ebb5af-c0df-5f47-97ba-27ab76d3f085")
│   inputs =
│    Dict{String, Any} with 2 entries:
│      "FILE"    => "file1"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
┌ Info: 2023-07-14 16:16:20 Finished: Command Program
│   command_running = `julia prog1.jl file1 abcdf`
│   run_id = UUID("d6ebb5af-c0df-5f47-97ba-27ab76d3f085")
│   inputs =
│    Dict{String, Any} with 2 entries:
│      "FILE"    => "file1"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
(true, Dict{String, Any}())

shell> cat .d6ebb5af-c0df-5f47-97ba-27ab76d3f085
i	1.689362179773261e9	6	FILE	file1
```

The run ID file only records FILE, and skips `prog1.jl` because it is not in inputs/outputs. If your external program code changes often, you need to put `prog1.jl` into inputs:

```julia
julia> prog = CmdProgram(cmd = `julia PROG FILE CONTENT`, inputs = ["FILE", "CONTENT", "PROG" => "prog1.jl"])
CmdProgram:
  name             → Command Program
  id_file          → 
  info_before      → auto
  info_after       → auto
  cmd_dependencies → <empty>
  arg_inputs       → FILE    :: Any (required)
                     CONTENT :: Any (required)
                     PROG    :: Any (default = prog1.jl)
  validate_inputs  → do_nothing
  prerequisites    → do_nothing
  cmd              → `julia PROG FILE CONTENT`
  infer_outputs    → do_nothing
  arg_outputs      → <Arg empty>
  validate_outputs → do_nothing
  wrap_up          → do_nothing
  arg_forward      → <empty>

julia> run(prog, FILE="file1", CONTENT="abcdf")
┌ Info: 2023-07-14 16:26:00 Started: Command Program
│   command_template = `julia PROG FILE CONTENT`
│   run_id = UUID("94e7cd7c-c360-5285-a788-fdb0d0692196")
│   inputs =
│    Dict{String, Any} with 3 entries:
│      "FILE"    => "file1"
│      "PROG"    => "prog1.jl"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
┌ Info: 2023-07-14 16:26:00 Finished: Command Program
│   command_running = `julia prog1.jl file1 abcdf`
│   run_id = UUID("94e7cd7c-c360-5285-a788-fdb0d0692196")
│   inputs =
│    Dict{String, Any} with 3 entries:
│      "FILE"    => "file1"
│      "PROG"    => "prog1.jl"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
(true, Dict{String, Any}())

shell> cat .94e7cd7c-c360-5285-a788-fdb0d0692196
i	1.6893627602452433e9	6	FILE	file1
i	1.6893615863252792e9	54	PROG	prog1.jl

julia> run(prog, FILE="file1", CONTENT="abcdf")
┌ Warning: 2023-07-14 16:26:38 Skipped finished program: Command Program
│   command_template = `julia PROG FILE CONTENT`
│   run_id = UUID("94e7cd7c-c360-5285-a788-fdb0d0692196")
│   inputs =
│    Dict{String, Any} with 3 entries:
│      "FILE"    => "file1"
│      "PROG"    => "prog1.jl"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
(true, Dict{String, Any}())

shell> touch prog1.jl

julia> run(prog, FILE="file1", CONTENT="abcdf")
┌ Info: 2023-07-14 16:26:51 Started: Command Program
│   command_template = `julia PROG FILE CONTENT`
│   run_id = UUID("94e7cd7c-c360-5285-a788-fdb0d0692196")
│   inputs =
│    Dict{String, Any} with 3 entries:
│      "FILE"    => "file1"
│      "PROG"    => "prog1.jl"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
┌ Info: 2023-07-14 16:26:51 Finished: Command Program
│   command_running = `julia prog1.jl file1 abcdf`
│   run_id = UUID("94e7cd7c-c360-5285-a788-fdb0d0692196")
│   inputs =
│    Dict{String, Any} with 3 entries:
│      "FILE"    => "file1"
│      "PROG"    => "prog1.jl"
│      "CONTENT" => "abcdf"
└   outputs = Dict{String, Any}()
(true, Dict{String, Any}())

```

**Comment by cihga39871** [comment]
You can put your script in inputs, so Pipelines can trace it. It is not necessarily to be a `.jl` file, but any file type except for .so, .dylib, .dll

If your script does end with .so, .dylib, .dll, you can do in place modifications to `Pipelines.RUN_ID_LINE_SKIP_EXTENSION`,
like:

```julia
julia> Pipelines.RUN_ID_LINE_SKIP_EXTENSION
3-element Vector{String}:
 ".so"
 ".dylib"
 ".dll"

julia> empty!(Pipelines.RUN_ID_LINE_SKIP_EXTENSION)
String[]

```

**Comment by jschepers** [comment]
Hi @cihga39871,
thanks a lot for your help and your detailed explanation. That's really helpful and we think we got it now! 
Best,
Judith
