### ISSUE TITLE
R Targets

### ISSUE THREAD

**Issue by tatakof** [cihga39871/Pipelines.jl#4]
do you have the intention of doing something like R's Targets package?

**Comment by cihga39871** [comment]
Hi @franfram , it is a good idea. Now Pipelines.jl is a tool to build small programs, and I think it is better to have something to connect those programs into pipelines. I am still thinking about how to do that. Do you have any thoughts on it?

**Comment by neosanma** [comment]
Hi Jiacheng Chuan. Thank you for your reply and for your effort on the Pipelines.jl package. 
Unfortunately, I don't have any thoughts on it (I'm no dev). I'm just looking towards a full transition from R to Julia for my research (probably in a few months) and I was browsing on GitHub to see if I could find everything I need. 

Looking forward to future releases of Pipelines.jl!

**Comment by cihga39871** [comment]
Thank you for your interest in Pipelines.jl!

Currently, an easy workaround that I have been used in my own project is to define a function, which calls multiple `Program`s. Since `Program` supports skipping finished tasks, the main function also has this feature.

For example:

```julia
program_a = CmdProgram(..., inputs = ["A", "B"], outputs = ["C"])
program_b = CmdProgram(..., inputs = ["C", "D"])

function pipeline(A, B, D)
    a_in = Dict("A" => A, "B" => B)
    a_out = run(program_a, a_in)

    a_out["D"] = D
    run(program_b, a_out)
end

```

**Comment by cihga39871** [comment]
From v0.8.6: a program will rerun when input files are newer than the run id file. Consider the issue solved.
